### ISSUE TITLE
Difficulty understanding tapping version of "then"

### ISSUE THREAD

**Issue by klop** [khanlou/Promise#28]
Apologies if this isn't the best place to ask, but I'm having difficult understanding what's going on in this function, more specifically: why do we create a promise that's seemingly not used for anything? Thanks!

https://github.com/khanlou/Promise/blob/f5b2821447d8411909f7b94d39f81e7b2efe44a9/Promise/Promise.swift#L187-L202

**Comment by khanlou** [comment]
Oh, haha. This is a fine place to ask.

The reason this version of `tap` is written like this is purely path-dependent. The original version of `tap` returned the new promise, but because you might use an `InvalidatableQueue` for the `ExecutionContext`, I wanted to make sure we returned a completing promise as often as possible. (If the queue was invalidated, then the promise returned here would never fulfill, meaning that any promises chained off of it would also never fulfill.)

I think we can just get rid of the "new Promise" wrapper, and it should still work exactly as expected. I won't have a chance to look for a while, but if you want to make the change and run the tests I would be open to a PR!
