### ISSUE TITLE
Suggestion: map & flatMap?

### ISSUE THREAD

**Issue by danielt1263** [khanlou/Promise#8]
I recall some issue with Swift's implicit typing and the overloading of `then`. It seems that because `then` is so overloaded, we end up having to explicitly type some closures.

I was thinking that it would help the type system and make our code more expressive if the `then` overloads were replaced with `map` and `flatMap` as appropriate. 

One con for this change would be that it moves away from the A+ spec, but we aren't programming in javascript so I don't think that should be an issue. Another con would be that this would be a breaking change. Maybe both could be implemented with `then` deprecated for a version?

If this suggestion is acceptable, I would be happy to update the code... What say you?

**Comment by khanlou** [comment]
When designing this library, I explicitly left out `map` and `flatMap`. The current behavior of `then` is a lot easier to understand, especially for beginners, and since JavaScript popularized Promises, I don't see a reason to move away from its conventions.

If you want `map` and `flatMap`, check out [BrightFutures](https://github.com/Thomvis/BrightFutures), or feel free add them in an extension and forward the behavior to one of the `then` overloads.

Further, a lot of the issues around having to explicitly type closure parameters are not because of overloading, but rather because while Swift will happily infer types for parameters/return values for single line closures, it won't for multi-line.
